// Programs CRUD routes:

Router.map(function() {
  // programsIndex: reactive tabular listing of all programs with CRUD UI. It auto-updates as a
  // subscriber to "programs" publications (see server/publications/programs.js)
  this.route('programsIndex', {
    template: 'programsIndex',
    path: '/programs',
    waitOn: function () {
      return Meteor.subscribe('programs');
    },
    data: {
      programs: function () {
        return Programs.find({}, {sort: {created: -1}});
      }
    }
  });

  // CREATE program route
  // Form is generated by AutoForm based on program collection schema
  // See: TODO document form generation
  this.route('programCreate', {
    template: 'programCreate',
    path: '/programs/add'
  });

  // READ program dynamic route, subscriber to program publication
  this.route('programView', {
    template: 'programView',
    path: '/programs/:_id',
    waitOn: function () {
      return Meteor.subscribe('program', this.params._id);
    },
    data: function () {
      return Programs.findOne(this.params._id);
    }
  });

  // UPDATE route
  this.route('programUpdate', {
    template: 'programUpdate',
    path: '/programs/:_id/update',
    waitOn: function () {
      return Meteor.subscribe('program', this.params._id);
    },
    data: function () {
      return Programs.findOne(this.params._id);
    }
  });


});
